export const SET_USER_PHONE = 'SET_USER_PHONE'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_NICKNAME = 'SET_NICKNAME'
export const SET_USER_IMAGE_URL = 'SET_USER_IMAGE_URL'
